apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pema-deploy
  name: pema-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pema-deploy
  template:
    metadata:
      labels:
        app: pema-deploy
    spec:
      containers:
      - image: kezangyuden/pemac:latest
        name: pet
